[package]
name = "raven"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
thiserror = "2.0.12"

[build]
target = "wasm32-unknown-unknown"
