[package]
name = "raven"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = true

[dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }
thiserror = "2.0.12"

[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']