[package]
name = "raven"
version = "0.1.0"
edition = "2024"

[dependencies]
getrandom = { version = "0.3", features = ["wasm_js"] }

[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']