[package]
name = "raven"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = true


[features]
default = []
# web = ["wasm-bindgen"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
thiserror = "2.0.12"
wasm-bindgen = "0.2.100"

[build]
target = "wasm32-unknown-unknown"
